import type { VenueAdapter } from "./types.js";
import type { NormalizedMarket, ResolutionStatus } from "../schema.js";

const LIMITLESS_BASE = "https://api.limitless.exchange";

interface LimitlessMarket {
  address: string;
  title: string;
  description?: string;
  slug?: string;
  stableSlug?: string;
  prices?: number[];
  liquidity?: string | number;
  liquidityFormatted?: string;
  volume?: string | number;
  volumeFormatted?: string;
  openInterest?: string | number;
  expirationDate?: string;
  expired?: boolean;
  closed?: boolean;
  resolved?: boolean;
  automationType?: string;
  marketType?: string;
  tags?: string[];
  conditionId?: string;
  positionIds?: string[];
}

const AUTO_TITLE_RE = /(?:price|above|below)\s.*\b\d{1,2}:\d{2}\s*UTC\b|\bon\s\w+\s\d+,\s*\d{1,2}:\d{2}\s*UTC/i;

function isAutoGenerated(m: LimitlessMarket): boolean {
  if (typeof m.automationType === "string" && m.automationType.toLowerCase() === "lumy") return true;
  if (Array.isArray(m.tags)) {
    for (const t of m.tags) {
      if (typeof t === "string" && t.toLowerCase() === "lumy") return true;
    }
  }
  if (m.title && AUTO_TITLE_RE.test(m.title)) return true;
  return false;
}

function n(v: string | number | undefined): number | undefined {
  if (v === undefined || v === null) return undefined;
  const x = typeof v === "string" ? Number(v) : v;
  return Number.isFinite(x) ? x : undefined;
}

function inferResolutionStatus(m: LimitlessMarket): ResolutionStatus {
  if (m.resolved === true) return "settled";
  if (m.closed === true || m.expired === true) return "closed_pending_resolution";
  return "open";
}

function toNormalized(m: LimitlessMarket): NormalizedMarket {
  const yesProb = m.prices?.[0] != null ? m.prices[0] / 100 : 0;
  const noProb = m.prices?.[1] != null ? m.prices[1] / 100 : Math.max(0, 1 - yesProb);
  const isAuto = isAutoGenerated(m);

  return {
    venue: "limitless",
    venue_market_id: m.address,
    event_id: m.stableSlug ?? m.conditionId,
    question: m.title,
    description: m.description,
    outcomes: [
      {
        label: "YES",
        probability: yesProb,
        tradable_outcome_id: m.positionIds?.[0],
      },
      {
        label: "NO",
        probability: noProb,
        tradable_outcome_id: m.positionIds?.[1],
      },
    ],
    liquidity_usd: n(m.liquidity),
    volume_usd: n(m.volume),
    open_interest_usd: n(m.openInterest),
    ends_at: m.expirationDate,
    resolution_status: inferResolutionStatus(m),
    settlement_risk: "low",
    settlement_risk_reason: "limitless deterministic pyth oracle resolution",
    chain: "base",
    collateral_token: "USDC",
    is_parlay: false,
    is_auto_generated: isAuto,
    url: m.slug
      ? `https://limitless.exchange/markets/${m.slug}`
      : `https://limitless.exchange/markets/${m.address}`,
    raw: m,
  };
}

function unwrap(raw: unknown): LimitlessMarket[] {
  if (Array.isArray(raw)) return raw as LimitlessMarket[];
  const obj = raw as { data?: LimitlessMarket[]; markets?: LimitlessMarket[] };
  return obj.data ?? obj.markets ?? [];
}

export class LimitlessAdapter implements VenueAdapter {
  readonly venue = "limitless" as const;

  async searchMarkets(query: string, limit = 10): Promise<NormalizedMarket[]> {
    const res = await fetch(`${LIMITLESS_BASE}/markets/active`);
    if (!res.ok) throw new Error(`limitless search failed: ${res.status}`);
    const list = unwrap(await res.json());
    const q = query.toLowerCase();
    return list
      .filter((m) => m.title.toLowerCase().includes(q))
      .filter((m) => !isAutoGenerated(m))
      .slice(0, limit)
      .map(toNormalized);
  }

  async getMarket(venueMarketId: string): Promise<NormalizedMarket | null> {
    // Limitless markets endpoint accepts either address or slug
    const trimmed = venueMarketId.trim();
    const res = await fetch(`${LIMITLESS_BASE}/markets/${encodeURIComponent(trimmed)}`);
    if (res.status === 404) {
      // try active list and match
      const active = await fetch(`${LIMITLESS_BASE}/markets/active`);
      if (!active.ok) return null;
      const list = unwrap(await active.json());
      const found = list.find(
        (m) => m.address === trimmed || m.slug === trimmed || m.stableSlug === trimmed,
      );
      return found ? toNormalized(found) : null;
    }
    if (!res.ok) throw new Error(`limitless getMarket failed: ${res.status}`);
    const json = (await res.json()) as LimitlessMarket;
    return toNormalized(json);
  }

  async listActive(limit = 25): Promise<NormalizedMarket[]> {
    const res = await fetch(`${LIMITLESS_BASE}/markets/active`);
    if (!res.ok) throw new Error(`limitless listActive failed: ${res.status}`);
    const list = unwrap(await res.json());
    return list
      .filter((m) => !isAutoGenerated(m))
      .slice(0, limit)
      .map(toNormalized);
  }
}
